swagger: "2.0"
info:
  description: File Swagger ini adalah dokumentasi dari aplikasi 
  version: "1.0.0"
  title: Swagger File
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths: 
  /milestone:
    get:
      operationId: milestone.ambil_data
      tags:
        - Milestone
      summary: Mengambil semua data milestone
      description: Mengambil semua data milestone, dan diurutkan berdasarkan kode prioritasnya
      responses:
        200:
          description: Ambil semua data milestone sukses
          schema:
            type: array
            items:
              properties:
                milestone_id:
                  type: integer
                  description: id dari data milestone
                milestone_title:
                  type: string
                  description: judul dari milestone
                milestone_description:
                  type: string
                  description: deskripsi dari milestone
                milestone_priority:
                  type: integer
                  description: kode prioritas dari milestone
                milestone_status:
                  type: string 
                  description: status dari milestone
                milestone_timestamp:
                  type: string
                  description: waktu tambah atau update data milestone

    post:
      operationId: milestone.tambah_data
      tags:
        - Milestone
      summary: Menambah data milestone
      description: Menambah data milestone
      parameters:
        - name: milestone
          in: body
          description: data milestone yang akan ditambahkan
          required: true
          schema:
            type: object
            properties:
              milestone_title:
                type: string
                description: judul dari milestone
              milestone_description:
                type: string
                description: deskripsi dari milestone
              milestone_priority:
                type: integer
                description: kode prioritas dari milestone
              milestone_status:
                type: string 
                description: status dari milestone
      responses:
        201:
          description: tambah data milestone sukses
          schema:
            properties:
              milestone_id:
                type: integer
                description: id dari data milestone
              milestone_title:
                type: string
                description: judul dari milestone
              milestone_description:
                type: string
                description: deskripsi dari milestone
              milestone_priority:
                type: integer
                description: kode prioritas dari milestone
              milestone_status:
                type: string 
                description: status dari milestone
              milestone_timestamp:
                type: string
                description: waktu tambah atau update data milestone

    put:
      operationId: milestone.update_data
      tags:
        - Milestone
      summary: Merubah data milestone
      description: Merubah data milestone
      parameters:
        - name: milestone_id
          in: path
          description: id milestone yang akan diupdate/dirubah
          type: integer
          required: true
        - name: milestone
          in: body
          description: data milestone yang akan diupdate
          required: true
          schema:
            type: object
            properties:
              milestone_title:
                type: string
                description: judul dari milestone
              milestone_description:
                type: string
                description: deskripsi dari milestone
              milestone_priority:
                type: integer
                description: kode prioritas dari milestone
              milestone_status:
                type: string 
                description: status dari milestone
      responses:
        200:
          description: Update data milestone sukses
          schema:
            properties:
              milestone_id:
                type: integer
                description: id dari data milestone
              milestone_title:
                type: string
                description: judul dari milestone
              milestone_description:
                type: string
                description: deskripsi dari milestone
              milestone_priority:
                type: integer
                description: kode prioritas dari milestone
              milestone_status:
                type: string 
                description: status dari milestone
              milestone_timestamp:
                type: string
                description: waktu tambah atau update data milestone

    delete:
      operationId: milestone.hapus_data
      tags:
        - Milestone
      summary: Menghapus data milestone
      description: Menghapus data milestone berdasarkan id
      parameters:
        - name: milestone_id
          in: path
          type: integer
          description: id milestone yang akan dihapus
          required: true
      responses:
        200:
          description: Hapus data milestone sukses
